---
- block:
    - include: initialize/service.yml
    - include: initialize/endpoints.yml
    - include: initialize/user.yml

  environment:
    OS_PROJECT_DOMAIN_NAME:  default
    OS_USER_DOMAIN_NAME:     default
    OS_PROJECT_NAME:         admin
    OS_USERNAME:             admin
    OS_PASSWORD:             '{{ keystone_admin_password }}'
    OS_AUTH_URL:             'http://{{ keystone_host }}:35357/v3'
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION:    2
